# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate tiktoken-rs

Name:           rust-tiktoken-rs
Version:        0.9.1
Release:        %autorelease
Summary:        Library for encoding and decoding with the tiktoken library in Rust

License:        MIT
URL:            https://crates.io/crates/tiktoken-rs
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Library for encoding and decoding with the tiktoken library in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-openai-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-openai-devel %{_description}

This package contains library source intended for building other packages which
use the "async-openai" feature of the "%{crate}" crate.

%files       -n %{name}+async-openai-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dhat-heap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dhat-heap-devel %{_description}

This package contains library source intended for building other packages which
use the "dhat-heap" feature of the "%{crate}" crate.

%files       -n %{name}+dhat-heap-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
